### ISSUE TITLE
Asian characters are not properly set

### ISSUE THREAD

**Issue by SonicoXD** [xavery/dcue#2] opened 2019-09-21 03:08 UTC
First of all, thanks for this amazing program, as well as this fork. It's a time saver.
Generating a .cue file for SuganoMusic - Eurobeat Festival Vol.2 [r9922074] resulted in all japanese characters/words being replaced by a set of numbers and slashes.
Here's the generated .cue file:
[SuganoMusic - EUROBEAT FESTIVAL VOL.2.txt](https://github.com/xavery/dcue/files/3638253/SuganoMusic.-.EUROBEAT.FESTIVAL.VOL.2.txt)

**Comment by lighterowl** [comment] 2019-09-21 08:16
This is now fixed in the development branch by replacing the home-grown JSON parser with [`nlohmann::json`](https://github.com/nlohmann/json), however you should be aware that compatibility with CUE-reading programs is going to be minimal at best. Characters like these are encoded in UTF-8 when produced by DCue, while there is no standardized character encoding when it comes to CUE files : most Windows programs are probably going to assume that the file is encoded in the local code page (aka "Active Code Page" also known as ACP, which is CP1251 in most English-speaking locales), producing garbage.
Also, this text must be converted into CD-TEXT when burning a CD file with a given CUE file. However, CD-TEXT doesn't define the character encoding which needs to be used, and hardware support for non-ASCII characters varies greatly, with most hardware choosing to interpret 8-bit characters according to the market they're targeting. Perhaps there were Asian CD players which interpreted CD-TEXT according to Asian multibyte encodings, but that remains to be seen...

**Comment by SonicoXD** [comment] 2019-12-09 04:07
> This is now fixed in the development branch by replacing the home-grown JSON parser with [`nlohmann::json`](https://github.com/nlohmann/json), however you should be aware that compatibility with CUE-reading programs is going to be minimal at best. Characters like these are encoded in UTF-8 when produced by DCue, while there is no standardized character encoding when it comes to CUE files : most Windows programs are probably going to assume that the file is encoded in the local code page (CP1251 in most English-speaking locales), producing garbage.
> Also, this text must be converted into CD-TEXT when burning a CD file with a given CUE file. However, CD-TEXT doesn't define the character encoding which needs to be used, and hardware support for non-ASCII characters varies greatly, with most hardware choosing to interpret 8-bit characters according to the market they're targeting. Perhaps there were Asian CD players which interpreted CD-TEXT according to Asian multibyte encodings, but that remains to be seen...

I'm compiling the develop branch on Linux but it still encodes unicode characters as before... Is there something that has to be changed manually?

**Comment by lighterowl** [comment] 2019-12-09 07:27
Sorry, can't reproduce. Running `dcue 9922074 foo.wav` results in the following CUE file being produced :
```
REM GENRE Eurobeat
REM DATE 2016
REM COMMENT "DCue v1.2dev"
PERFORMER "Various"
TITLE "Eurobeat Festival Vol. 2"
FILE "foo.wav" WAVE
	TRACK 01 AUDIO
		TITLE "Everlasting"
		PERFORMER "Shironegi"
		INDEX 01 00:00:00
	TRACK 02 AUDIO
		TITLE "Boom Boom Lovin' Desire"
		PERFORMER "紅梔子"
		INDEX 01 05:24:00
	TRACK 03 AUDIO
		TITLE "Dear Mr.Heartbreaker"
		PERFORMER "Rin"
		INDEX 01 09:52:00
	TRACK 04 AUDIO
		TITLE "バグズ・ナイト"
		PERFORMER "紅梔子"
		INDEX 01 14:44:00
	TRACK 05 AUDIO
		TITLE "Midnight Shot!! 2016"
		PERFORMER "紅梔子 ノイズ"
		INDEX 01 19:36:00
	TRACK 06 AUDIO
		TITLE "Eurobeat Ninja Comes Again"
		PERFORMER "nmk"
		INDEX 01 24:28:00
	TRACK 07 AUDIO
		TITLE "Oblivion Phantasm"
		PERFORMER "Setuna"
		INDEX 01 28:32:00
	TRACK 08 AUDIO
		TITLE "Real Hero (Haseko × Sato. Edit)"
		PERFORMER "紅梔子"
		INDEX 01 32:43:00
	TRACK 09 AUDIO
		TITLE "Sadness Memory"
		PERFORMER "橘花音"
		INDEX 01 39:05:00
	TRACK 10 AUDIO
		TITLE "Peerless Gale"
		PERFORMER "かなえゆめ"
		INDEX 01 43:07:00
	TRACK 11 AUDIO
		TITLE "Midnight Shot!! 2016 (Instrumental)"
		PERFORMER "Sugano"
		INDEX 01 47:45:00
	TRACK 12 AUDIO
		TITLE "Eurobeat Ninja Comes Again (Instrumental)"
		PERFORMER "nmk"
		INDEX 01 52:37:00
	TRACK 13 AUDIO
		TITLE "Oblivion Phantasm (Instrumental)"
		PERFORMER "Haseko"
		INDEX 01 56:39:00
```
Are you sure that you're actually running the newest version, i.e. have you pulled and recompiled? Because I really don't know what else could cause the problem.

**Closed as completed** 2020-08-10 21:49 UTC
